// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/29/2026, 1:53:37 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/plugins/**/*.{js,ts,mjs}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/composables/**/*.{js,ts,mjs}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/utils/**/*.{js,ts,mjs}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/vincent.zhen24/Documents/GitHub/vue-supabase-project-2026-clockwise/nuxt-app/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;